# .github/workflows/ci.yml
name: CI

# main dalına her push ve pull_request yapıldığında tetiklenir
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    # GitHub'ın en güncel Ubuntu sanal makinesinde çalışır
    runs-on: ubuntu-latest

    # Dilerseniz Node sürüm matrix’i ile test edebilirsiniz
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # 1) Depoyu klonla
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Node.js’i kur
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 3) NPM cache’ini koru (hız için)
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4) Bağımlılıkları yükle
      - name: Install dependencies
        run: npm ci

      # 5) Testleri çalıştır
      - name: Run tests
        run: npm test -- --watchAll=false

      # (isteğe bağlı) 6) Build adımı
      #- name: Build
      #  run: npm run build
